language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest
notifications:
  slack:
    rooms:
      secure: qkNupMBY80Qquj0yEMrkvxvaYPnurnOQO1rpCCKMDpM2rzDRaUDBLx8l3j8bOOlb9ZqrxpWLpivjgLbe3g6ko6gakTUachy2qdLvSZLbKx6OkqcRaKo/+5R4lVuh7/YSCUgNrBELoHWbR4kDArJFkLs0TpYqy/PFw01EmGmObH7YlUpXn5EgD/X5ZawFYyknWMS6E+eDlfQR5yLUeHlOJFuuDdeGzmG7fGjlhSPM9lG9TeDMKFUbSQa75oZI9w+nLp1296QFot3B/BeBDtxsZSWIa/Ph4TtP7qNDlP8vomg5OrocQDhF63db4sZjMQovjNWUUediskguzleUmb+Y9TJhOPQdj/CHwfMfGUEp56l0fh6SNIk4UVsSz8Yam3VoPrqYzNCo8doA9K/VK9hyb/PmndGtTZvtLi7/MPgLljKsY6UFWOiHVittvF46S8QJODR5wkl5D1iwj3JzGUA7Gi5Drkfjj0Nf77m3uT7SEGNajAOkIOC8SY4yFJLxSx/KvS/EVZdAsndSKZ+fHXlhtb4SXeZm8BsTpnCuCbgYSjGVREhGWBeLVKg9ZYm8ssVw0EgEnb5Bna934sp8qS2QGMzaa+RaO/QY04dqftNASWrFyS18G2tXDxHcUh8h0hehYLJjtfEm+5E6/BAvsDMVhLCh7z085t9jEGhF9j1P5hw=
